# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'Astro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen'
  pod 'SwiftLint'

  target 'AstroTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
